blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name = 'index'),

    path('details/<int:article_id>/', views.details, name = 'details'),

    path('about', views.about, name = 'about')
]

blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

class Artikel(models.Model):
    penulis = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    judul = models.CharField(max_length = 200)
    isi = models.TextField()
    created_date = models.DateTimeField(default = timezone.now)

    def get_absolute_url(self):
        return reverse('blog:details', args=[str(self.id)])

    def __str__(self):
        return self.judul

blog/views.py
from django.shortcuts import render
from .models import Artikel

def index(request):
    context = {
        'articles' : Artikel.objects.all().order_by('-created_date')
    }
    return render(request, 'blog/index.html', context)

def details(request, article_id):
    context = {
        'article' : Artikel.objects.get(id = article_id)
    }
    return render(request, 'blog/details.html', context)

def about(request):

    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/about.css' %}"></link>
</head>
<body>
    <table>
        <tr>
            <th>Nama</th>
            <td>:</td>
            <td>Fawwaz Widya Aswangga</td>
        </tr>
        <tr>
            <th>NPM</th>
            <td>:</td>
            <td>52417271</td>
        </tr>
    </table>
</body>
</html>

blog/templates/blog/details.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ article }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/article.css' %}"></link>
</head>
<body>
    <a href="{% url 'blog:index' %}">Kembali ke Beranda</a>
    <h1>{{ article }}</h1>
    <h6>{{ article.penulis }}</h6>
    <h6>{{ article.created_date }}</h6>
    {{ article.isi }}
</body>
</html>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/index.css' %}"></link>
</head>
<body>
    <h1>Daftar Artikel</h1>
    {% for article in articles %}
        <a href="{{ article.get_absolute_url }}"><h2>{{ article }}</h2></a>
        <p>{{ article.isi|safe }}</p>
        {% endfor %}
    <a href="{% url 'blog:about' %}"><h2>Tentang Kami</h2></a>
</body>
</html>